version: '3.8'
services:
  php:
    build: 
      context: ./
      dockerfile: dockerfile
    container_name: crudphp-taller3
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./config:/usr/local/etc/php
volumes:
  html: {}
  config: {}

      